### PR TITLE
Update buildpack from archaelus to heroku.

### PR DESCRIPTION
**Pull request by tommay**
The archaelus  buildpack doesn't work.  Heroku provides one that does.

### CODE REVIEW

**Comment by 6** [comment]
good catch, it looks like the heroku repo is actually being un-deprecated.

The archaelus fork only works if you run `heroku stack:set cedar` to use the old cedar stack

**Comment by tommay** [comment]
I filed an issue on the heroku version asking them to clarify the deprecated status since the README is inconsistent and the commit log says things about it being undeprecated.

**Comment by tommay** [comment]
Archaelus says the heroku version is in the process of being undeprecated, and to use it.  So we're good.
https://github.com/heroku/heroku-buildpack-erlang/issues/6#issuecomment-75671280

**Comment by 6** [comment]
Awesome! Thanks for checking

**Pull request merged**
